spring:
  application:
    name: courses-api
  datasource:
    url: jdbc:mysql://localhost:3306/courses-api?createDatabaseIfNotExist=true
    username: ${dbUser} # your username
    password: ${dbPassword} #your password
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 72000 #5 min
    refreshTokenExpiration: 604800 # 7 days
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
websiteUrl: http://localhost:4242